
Last year, [Aaron Fisher](http://aaronjfisher.github.io/) spoke at a computing club about a text expander named [Typinator](http://www.ergonis.com/products/typinator/).  In the past year, I have used it for the majority of my LaTeX and math writing and wanted to discuss a bit why I use Typinator.

### Seeing your Math symbols
The main reason I use Typinator is to expand text to [unicode](http://en.wikipedia.org/wiki/Unicode) -- symbols such as $β$ instead of writing \beta in LaTeX.  When I say "expand text" is I type a string that I set in Typinator and it replaces that string with the symbol or phrase that I designated as the replacement.  I type `:alpha` and out comes an $α$ symbol.  

### Why should you care
Writing \alpha or `:alpha` saves no time -- it's the same number of characters.  I like using unicode because I like reading **in the LaTeX**: 
$$
Y = X β + ε
$$
instead of 
```
Y = X \beta + \varepsilon
```
and "the $β$ estimate is" versus "the \$\beta\$ estimate is".  I think it's cleaner, easier to read, and easier to edit.  One problem is: unicode doesn't work with LaTeX right off.

### `pdflatex` doesn't show my characters! Use XeLaTeX

Running `pdflatex` on your LaTeX document will not render these unicode symbols out of the box, depending on your encoding.  Using the package LaTeX `inputenc` with a command such as `\usepackage[utf8x]{inputenc}` can incorporate unicode (according to [this StackExchange Post](http://tex.stackexchange.com/questions/34604/entering-unicode-characters-in-latex)), but I have not used this so I cannot confirm this.

I use [XeLaTeX](http://en.wikipedia.org/wiki/XeLaTeX), which has inherent unicode support.  In my preamble I have

```
\usepackage{ifxetex}
\ifxetex
  \usepackage{unicode-math}
  \setmathfont{[Asana-Math]}
\fi
```
to tell the compiler that I want this font for my math.  I then run the `xelatex` command on the document and the unicode $α$ symbol appears in the PDF and all is right with the world.  

You can also incorporate `xelatex` in your `knitr` documents in RStudio by going to `RStudio -> Preferences -> Sweave Tab -> Typset LaTeX into PDF using` and change this option to `XeLaTeX`.  Now you're ready to knit with unicode!


## Other uses for Unicode than LaTeX
If you don't use LaTeX, this information above is not relevant to you but Unicode can be used in other settings than LaTeX.  Here are some instances where I use Unicode other than LaTeX:

1.  Twitter.  Using β or ↑/↓ can be helpful in conveying information as well as [saving characters](https://twitter.com/StrictlyStat/status/466317463899357184) or writing things [such as 𝜃̂](https://twitter.com/StrictlyStat/status/324231037083348993).
2.  E-mail.  Using symbols such as σ versus \sigma are helpful within Gmail or when emailing a class (such as in CoursePlus) for conveying information **within the email** compared to attaching a LaTeX'd PDF.
3.  Word Documents.  I don't like the Microsoft Word Equation Editor.  By don't like I mean get angry with and then stop using.  Inserting symbols are more straightforward and using a text expansion is easier than clicking them on the symbol keyboard.
4.  Grading. When annotating PDFs for grading assignments, many times I use the same comment -- people tend to make the same errors.  I make a grading typeset where I can write a small key such as `:missCLT` for missing the Central Limit Theorem in a proof so that I type less and grade faster.  Who doesn't want to grade faster?
5.  Setting Variables.  I don't do this nor do I recommend it, but **technically** in `R` you can use unicode to set a variable:

```{r}
σ = 5
print(σ)
```


## My Typinator sets.
My set of Typinator keys that you can download and import into Typinator are located here.  

1.  [Math Symbols](https://github.com/muschellij2/HopStat/tree/gh-pages/Typinator/Math_Set.tyset) for Greek and other math-related symbols. (This was my first typeset so not well organized.)
2.  [Bars](https://github.com/muschellij2/HopStat/tree/gh-pages/Typinator/bars.tyset) for making bars on letters such as 𝑥̄.
3.  [Hats](https://github.com/muschellij2/HopStat/tree/gh-pages/Typinator/hats.tyset) for making hats on letters such as 𝜃̂.
4.  [Arrows](https://github.com/muschellij2/HopStat/tree/gh-pages/Typinator/Arrows.tyset) just ↑ and ↓ for now.  

NB: GitHub thinks the `.tyset` file is a folder and not an object, so the .txt files are here for [Math Symbols](https://github.com/muschellij2/HopStat/blob/gh-pages/Typinator/Math_Set.txt), [Bars](https://github.com/muschellij2/HopStat/blob/gh-pages/Typinator/bars.txt),  [Hats](https://github.com/muschellij2/HopStat/blob/gh-pages/Typinator/hats.txt), and [Arrows](https://github.com/muschellij2/HopStat/blob/gh-pages/Typinator/Arrows.txt), which can be imported into Typinator.

If you comment, be sure to use a Unicode.   symbol
