So you got invited to an open house after you applied for your PhD.  Now you get to visit the university, see the faculty and students, and meet the department overall.  Here are some pointers that I have picked up over the years, things to ask if you freeze up and can't think, and things to look for when visiting.  I'll try to discuss things that are relevant to PhD and Master's students, but I'm currently a PhD student, so these tips may be more applicable to a PhD.

## What is grad school?
I've been around for some time, and let me tell you one thing: **you are more prepared than when I was looking at graduate schools and programs**.  When I applied, I essentially Googled "What can you do with a biomathematics degree?" and biostatistics came up and off I went applying.  Not a very rigorous or studious way of doing things, but I think it worked out.  So what is grad school? For one thing I can definitively say for me: **it is not undergrad**.  My undergrad is not a research institution and I hadn't done any heavy programming or even knew what markdown was (nor [LaTeX](http://www.latex-project.org/) or [R](http://cran.r-project.org/) ).  I also didn't realize it wasn't common to wear shorts, a t-shirt, and a backwards hat to class.  So if you know this, you are more prepared than I was.

## School Determination
It's a little late for this, but the first thing you need to do is pick a school that has the program you want.  For a Master's degree, that means the program you want to study and **at an affordable price**.  I didn't thoroughly weigh the cost of my education across programs, which I regret.  I believe I stil made the best choice, but a more informed financial decision would still have been better.

## Questions
Here I'll go through some questions you can ask if you don't feel like you know what to ask when you get there. I'll break them up into overall, for other students, for professors, as these 3 audiences are different in what and how you should ask questions.

### Questions to ask overall
These are questions you can, and should, ask in a big group so that other students can hear the responses as well.  They may be asked to administrators or the graduate program director, as well as other students.

1.  What are some examples of departmental events?
2.  What resources does the department have for new students? 
3.  What resources does the deparmtent have? e.g. a computing cluster, money for students books/a new computer
4.  Do students (which students) get offices (if any)?  
5.  How big is the department?
6.  What are the requirements for graduation (comps, orals, dissertation, etc)?

### Questions to ask students
These are usually much more informal than those to the professors or staff.  The level of informality can inform whether the student body fits well with your personality.

1.  What is student life like?
2.  Does the stipend cover the cost of living?
3.  What neighborhoods do you live in?
4.  How much does rent usually cost?
5.  How much does a cheeseburger and/or beer cost at a restaurant you usually go to?  This is a question that can give you an idea of how much the cost of living is.
6.  Do you have/need a car?
7.  What is the public transportation like (do you ride the bus, do you usually cab, etc)?
8.  How much interactions do you have with professors that aren't your advisor/teacher?  When I was interviewing at another department, I told one of their students that I was interviewed by Professor X (not [Xavier](http://en.wikipedia.org/wiki/Professor_X)), and they replied "Oh, I don't know who that is."  That told me a lot of how the department operated, and I realized I liked smaller departments.
9.  What student groups exist?  This is interesting because it'll let you know how the students interact.  For example, we have a computing club, a journal club, and an informal blog meeting.


### Questions to ask professors
These are more formal in some respects and allow you to find out what research people are really doing and see if you connect with anyone.

1.  What is the coolest thing you've done recently?
2.  How many students do you have under you, on average?
3.  How often do you meet with your students?
4.  How many classes do you teach a year?
5.  How many students of yours have graduated?  This is biased against new professors, but they should let you know that they are new.
6.  How are your students funded?  Do they find funding or do you have funding usually available?

## Be yourself
The main message I can send is: be yourself.  For however cliche it is, being yourself will let you accurately know if you get along with the department or their students.  Some personalities just don't go with certain departments or certain professors, but that's not constrained to grad school.  It's good to get as much information as the "feel" of the department and if you fit there by the end of the visit.

## Like where you live
Lastly, I think the best advice about choosing a department for a PhD was given from a [friend of mine](http://www.linkedin.com/pub/christopher-barr/65/a28/455): "live somewhere you would like to live for the next 5 years".  I'd say the same thing for a 2-year or 18-month long Master's degree.  The department can be great, but liking where you live is a huge component of maximizing happiness while you're in graduate school.  And that should be #2 on your list, right after "getting it done".




