I'm helping out with teaching a class on an introduction to R for students this week. I figured it'd be a good time to discuss my thoughts on programming in R and how a newcomer should feel about learning the language.

## Those Who Teach R, Should Use R
Many of the students in the class at the beginning are overwhelmed.  They see a bunch of different symbols and syntax; being overwhelmed is understandable.  Moreover, those teaching you R can seem lightning fast when running code, moving around screens, or figuring out problems, and they usually are.  Do you know why?
> Those who are teaching you R, use R.  They use R a lot.  They use it daily, and for hours a day usually.  Don't try to be them immediately, get the basics.

I hear students saying "Oh, you're fast" when power users help them, usually lined with an undertone of low self-esteem.  That's like me going to a basketball camp run by Michael Jordan and saying "Oh man Michael, you're really good on the court".  Be like Mike: work hard to learn the basics like the back of your hand.  You'll be dunking in no time.

And, of course, those who teach you are fast.  Why would you take class from someone slow or unsure while doing what they're teaching you?  Yes, your teachers may be fast, but that's the point.  Learn from those who do.

I feel as though I'm relatively fast on my machine and I felt this starting out.  Even more, I didn't know what [tab completion](http://en.wikipedia.org/wiki/Command-line_completion) was when starting out my first class. I thought my professor could actually type **that** fast when writing variables or directory paths.  I thought it was magic.  If I didn't stick it out, I wouldn't figure out how to make that magic myself.  

## R is a language
I took Spanish in high school for 4 years.  I remember some vocabulary words and some conjugation rules, but am far from conversational.  I've never taken French -- I don't know French.  Now, if I took an introduction to French class for 4 hours, do you think I could speak (or write) French fluently?  No, of course not.  Yet students think they can with R.  My Spanish is like a background in Stata: some words/phrases/commands are similar, other are misleading and can be confusing.  

R is a programming **language**. Just like a foreign language, R has syntax and grammar.  You must learn simple punctuation such as placement of commas, assigment using "=" or "<-", where to close parentheses, and when to notice when a quote is unmatched.  My overall message is:
> R is a language, treat it like one.

Remember to tell students to hold themselves to the same level of comprehension as they would for a spoken (or signed) or written language.  Hopefully, that will put learning R in perspective, even if it does not make it any less overwhelming.  I wonder if Rosetta Stone will make an R module one of these days.