
FYI: This post is non-academia in nature.  TL;DR: Some friends and I created a scholarship for our high school and you should too.

## What happened?
My alma mater high school is [Sun Valley](http://www.pdsd.org/Domain/92), located in Aston, Pennsylvania, my hometown.  Last year around this time, I saw [two brothers started a $1,000 micro-scholarship for their former high school](http://makezine.com/2013/05/20/making-maker-scholarships/)  (also in Pennsylvania).  I loved the idea: be the other person on the scholarship award ceremony, the one giving the award.  

A few friends of mine said why not, let's make our own scholarship: the Vanguard (our mascot). With the help of one of our friends who happens to work in the guidance department of Sun Valley, we put together a requirement list and description of questions to answer.  

The questions we asked were:

1.  If you could go back and go through high school over again, what would you do differently?
2.  What is the best and worst qualities of your generation?
3.  How did growing up in Delco (Delaware County) shape you?


## How did it work out?

Overall, we collected $200 per person just for the starter year and hope to do some fundraising events next year.  We received a small number of applicants, due to the inclusion criteria and the timeliness of our submission (we were late).  I think it was a success and want to just make some notes if you want to try this out at your school.  

2.  You'd be surprised how many people are willing to donate money to their alma mater high school.    
3.  Begin early and work with the staff at school.  They have done this before, many many times.
4.  Make the inclusion criteria liberal - I surprisingly liked reading the responses from students and would have liked more.
5.  Even if you cannot or do not want to donate money, you can always go back and donate your time.  We have heard (and even thought in high school): "What has anyone done who graduated here"?  This feeling may be more common in public schools, where the alumni boards are non-existent or not as present as private schools.  Be a role model.  You (literally) were in these student's seats not too long ago.  Show them they have connections and can see someone who has succeeded.  Don't sell yourself short - you've likely succeeded in far more ways than you perceive.  
6.  Don't listen to haters.  I believe if people are putting you down or saying that what you're doing is "dumb" or something else derogatory, they've got some stuff going on.  Leave them and their words be.



## But I already donate to my college!
Many people that have jobs at my age give infrequently or not at all to their undergrad alma mater.  I get calls from [the University of Scranton](http://www.scranton.edu/), my undergrad, to donate and give back.  The callers are students at the university and tell me about what they are working on and how the school has changed.  

Some people may give you the "I already donated to my college". I think the demographic is different who donate to their high school than those who donate to their college.  Our high school is public, so I think you get less of the "I already paid thousands to my university" dismissal.  I like to think my schools had a strong hand in making the man I am, and would like to repay them. 

## How (and why) to start
Just think before reading this and going on your way: saying you created a scholarship an awesome thing to put on your resume and a conversation starter; it separates you from many others.

1.  Just get 5-10 people who are willing to donate a moderate amount of money.  It doesn't have to be sizable, many scholarships are under $300 - that's only $30 per person if you have 10 people.  
2.  Talk to your school and ask any paperwork you need to fill out.  
3.  Figure out an inclusion/exclusion criteria.
4.  Make a prompt/question for students to answer.  Allow cool submissions like videos, Vines, etc.
5.  Select your winner.  We just used [Survey Monkey](https://www.surveymonkey.com/) to have each person rank the winner.  We chose the best ranking as the top.  Ties were broken by total number of #1 votes (this happened). 
6.  Give the prize.  Try to get your donors to the awards banquet.

We will also ask students to give any updates on post-high-school endeavors so we can see how our recipients are doing.

### Side note: Network and political capital
I am not very political in nature, but for those who are, this is a great way to meet and network in your area.  Many of the local political and not political organizations and clubs donate scholarships to students.  This gets you a seat (literally) at the table.  Also, most people who donate are successful and you can enhance your network.  




