Teach Confidence Intervals as Weather
========================================================

Many times I find students struggling with the interpretation and meaning of confidence intervals in a frequentist framework. I have used two methods that seem to work well: a weather example and (of course) a coin flipping example.

## Weather ago
Some time ago, [Simply Statistics](http://simplystatistics.org/2012/10/30/on-weather-forecasts-nate-silver-and-the/) discussed how to look at Nate Silver's percentage estimates as weather forecasts, and I liked the post.  The [Weather Channel](http://feedback.weather.com/knowledgebase/articles/24439-weather-com-what-do-the-different-percentages-of-) describes what they mean by "a 40% chance of percipitation", but this quote is most relevant:

>[T]here is only a 40% chance that anyone in [the area in question] will receive precipitation.

Students can understand (frequentist) confidence intervals in the same capacity. We can think of it this way: the "area" is over a repeated experiments - your geographic area are repeated experiments and the we have an rain meter (or an estimator, in our case the confidence interval) for each of the areas.  

In the weather case, if the percentage is truly 40%, we think, on average, that 40% of the rain meters will have colected rain (cover the true parameter).  Now for each individual rain meter, it either collected rain or they did not, just like if there is a true parameter, the confidence interval either covered it or did not.  

This gives a concrete example to students about what confidence intervals mean in a frequentist framework.  The idea that there's a 95% chance the confidence interval covered the parameter is understadably expelled when you say: in a given rain meter, is there 95% chance there is rain? No, either it has rain or not.  

## 

