So a few know that I have a set of rules that I have made over the years that are some good guidelines for my life.  Some of them are not appropriate here, but I would like to share my Rule #2: Always Have a Pen.  (Rule #1 is not relevant for discussion.)

This may seem like a silly rule, but I feel like it has been useful for me in the past few years.  Amongst others, I first got this advice from [Dr. Charles Rohde](http://www.biostat.jhsph.edu/~crohde/personal/) during his class.  He simply stated that you should always have a pen (and paper) because good ideas/quotes rarely come when you expect them and it'd be a crime to forget them.  Others have good points on why to have one: [here](http://notesaboutnotes.com/Notes/Alwayshaveapen.html) and of course [Reddit](http://www.reddit.com/r/LifeProTips/comments/1bxtia/lpt_always_carry_a_pen_youll_find_you_use_it/).  You may want to skip this post and read the Reddit comments.


## Why I like pens
Some people may ask: Why a pen? Why not carry around a pencil?  To which I respond: "Who are you and what are you doing in my house?".

But honestly, one big thing is that pencil doesn't work very well on some surfaces, especially skin.  Particularly on the back of my hand, which is the first medium I use if I have no paper.  I also break the lead in pencils all the time.  I can write as hard as I want with a pen, and it almost never breaks.  Using an eraser on a pencil pretty much turns into an infectious smudge disease that makes whole pages indecipherable.  One other thing that I realized later in life: other than people who study math, many people use pens - it just seemed more grown up.  So I like using a pen.

## Why I hate pens
Really, the one reason I hate pens is because when you always have a pen, you sometimes wash a pen.  Note: pens stain clothes.  This has happened to me more than once, ruining almost entire loads of laundry.  Now I check all my pockets twice before doing laundry.  I guess this practice is good training if I have to wash my children's clothes one day (or have children).  

But pens don't ruin clothes only when in the wash. When you put pens in your pocket, you have to make sure they are are unclicked.  I have some nice lined khakis lying around somewhere if you'd like to see what I mean.  So if these are concerns or you'd have an aneurysm if pen got on your pants, maybe take that pencil route.  Or carry two pens: one ballpoint, one Tide.  Or get a pocket protector.  

Don't get a pocket protector.


## Ancillary Benefits

1.  When splitting a check, you can write down the amounts on multiple credit/debit cards.  The waiter/waitress almost never brings a pen <strong>before</strong> you give your cards, which I find as a bit of an oversight, unless they don't want you to split the check.  And I have [PayPal](https://www.paypal.com/) or [Venmo](https://venmo.com/) to do things electronically when needed, but pens still are handy.
2.  It's good when you have to write your number/email down really quick.  You can also add things to your business card (like a website or a message or Twitter handle), if you need to.
3.  You look professional and have your stuff together.  Ever see that person frantically looking in their bag or asking if someone has something to write with?  Amateurs.

## Conclusion
You may do all your thinking 9-5 or always have your phone/computer/tablet.  I frequently have my tech gear handy and have tried to become 100% digital, yet I still use pens.  I mostly use it during off hours and when I'm not in the office.  Sometimes I look like Russell Crowe from [A Beautiful mind](http://www.imdb.com/title/tt0268978/) writing down math equations on a napkin.  I'm OK with that, and much happier if I can get things down on paper (or napkin or skin) at the time I'm thinking rather than have the anxiety of forgetting it.  So if you want one quick "improvement" for the day, start carrying a pen.  If you already do, get a nice one - you won't be so apt to lose it.